version: '3'

services:
  pubsub-emulator:
    image:  google/cloud-sdk:352.0.0-emulators
    ports:
      - 8085:8085
    command: gcloud beta emulators pubsub start --host-port=0.0.0.0:8085
  postgresql:
    image: postgres:9.6-alpine
    healthcheck:
        test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
        timeout: 45s
        interval: 10s
        retries: 10
    env_file: comptest.env
    ports:
        - 5432:5432
    command: ["postgres", "-c", "log_statement=all"]