version: '3'

services:
  postgresql:
    image: postgres:9.6-alpine
    healthcheck:
        test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
        timeout: 45s
        interval: 10s
        retries: 10
    env_file: comptest.env
    ports:
        - 5432:5432
    command: ["postgres", "-c", "log_statement=all"]
